
# back.py

# In this file, all the backend is created. The data is modified and used.

import streamlit as st
import requests
import pandas as pd

"""API_reddit.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1TDOX5EZTTrHwFcLMlnA2nzQB9kuJflfO
"""

import os       #importing os to set environment variable
def install_java():
  !apt-get install -y openjdk-8-jdk-headless -qq > /dev/null      #install openjdk
  os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"     #set environment variable
  !java -version       #check java version
install_java()
!wget http://mallet.cs.umass.edu/dist/mallet-2.0.8.zip
!unzip mallet-2.0.8.zip